services:
  php-app:
    build: ./
    ports:
      - "9009:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ngn
      MYSQL_PASSWORD: ngn@ngn
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: ngn@ngn
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/db.sql
